### ISSUE TITLE
ban time set in lbanlist is not showing the correct time according to user timezone setting.

### ISSUE THREAD

**Issue by ZioNeL** [UndernetIRC/gnuworld#18] opened 2023-04-19 12:37 UTC
Hello.
I`ve noticed that the ban set time in LBANLIST command from X is not showing the correct time value from user timezone.
For example:
I`ve set a ban at 14:28 (Europe/Bucharest) this is also my timezone setting, but X shows this value: -X- SINCE: Wed Apr 19 08:28:07 2023 It seems that the timezone setting is ignored.

**Comment by hiddn** [comment] 2023-05-01 22:44
Hi. The timezone is not used anywhere in mod.cservice (nor am I seeing it anywhere else in gnuworld). The timezone setting only considered by mod.cservice's web interface.

**Comment by Compy** [comment] 2024-01-10 19:36
Closing this since its working as designed (and we have no plans to add timestamp localization to IRC text output).

We appreciate all you do @ZioNeL !

**Closed** 2024-01-10 19:36 UTC
